name: Build and Deploy

on:
    push:
        branches: [main, master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4

            - name: Checkout winget-pkgs repo
              uses: actions/checkout@v4
              with:
                  repository: microsoft/winget-pkgs
                  path: winget-pkgs
                  fetch-depth: 1

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Extract packages.json
              run: |
                  python extract_packages.py winget-pkgs/manifests/ packages.json

            - name: List manifest files
              run: ls -l winget-pkgs/manifests | head -20

            - name: Copy site assets
              run: |
                  cp index.html packages.json .

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./
                  publish_branch: gh-pages
                  force_orphan: true
